AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Naming/VariableName:
  Enabled: true